function [h] = CCmenu(chid,csta,hSDMfig,loc);

[nchid,nt] = size(chid);
stmonitr
width = width_cc*1.1;

height_1 = height_cc_1;
height = (nt+3)*height_1;
if(nargin < 4)
  loc = loc_cc;
end
rect_fig = [loc width height ];
h = figure('Position',rect_fig,'Name','Sta./Comp.',...
	'UserData',hSDMfig);
for k=1:nt
   rect = [ width*.1 (nt-k)*height_1+5 width*.7 height_1*.8];
   rect_two = [ width*.8 (nt-k)*height_1+5 width*.1 height_1*.8];

  name = [csta(:,k)' '  ' chid(:,k)' ];
  uicontrol('style','checkbox', ...
     'parent',h,...
     'position',rect,...
     'string',name,...
     'value',0,...
     'tag','Group 1',...
     'UserData',k,...
     'callback','CCmenuCB');
      
  uicontrol('style','checkbox', ...
     'parent',h,...
     'position',rect_two,...
     'string','',...
     'value',1,...
     'tag','Group 2',...
     'UserData',k,...
     'callback','CCmenuCB;');

end  %  loop over channels 1:nt

rect = [ width*.1 (nt+1.6)*height_1+5 width*.8 height_1*.8];
uicontrol('style','pushbutton', ...
   'parent',h,...
   'position',rect,...
   'UserData',nt,...
   'string','PLOT',...
   'Tag','PLOT',...
   'callback','CCmenuCB');
        
rect = [ width*.1 (nt+.5)*height_1+5 width*.8 height_1*.8];
uicontrol('style','pushbutton',...
	'parent',h,...
	'position',rect,...
	'string','QUIT',...
        'Tag','QUIT',...
	'callback','CCmenuCB');
