% "popup menu" for eigenvector plotting

%   figure handle of parent SDM figure (store as UserData in
%     the popmenu figure; also use this to retrieve present
%     settings for EVEC_OPTIONS)
hSdm = gcf;
UD = get(hSdm,'UserData');
EV = UD.EVEC;
EV.parentFig = hSdm;
evx0 = 300;evy0 = 100;evx=300;evy=400;
height = 25; space = 15;vspace = 5;
height_n = height/evy; space_n = space/evx;vspace_n = vspace/evy;
width2 = (1-3*space_n)/2;
width3 = (1-3*space_n)/3;
rect_main = [evx0,evy0,evx,evy];
x1 = space_n;
x2 = 2*(space_n)+width2; y = 1-height_n*2;
x3 = 1.5*(space_n)+width3; y = 1-height_n*2;
x4 = 2*(space_n)+width3*2; y = 1-height_n*2;
rect_nevec1 = [x1,y,width2 ,height_n];
rect_nevec2 = [x2,y,width2,height_n];
y = y - height_n - vspace_n;
rect_rhor1 = [x1,y,width2,height_n];
rect_rhor2 = [x2,y,width2,height_n];
y = y -(height_n+vspace_n);
rect_SNR = [x1,y,width2,height_n];
rect_pol = [x2,y,width2,height_n];
y = y - height_n-vspace_n;
rect_impNorm = [ x1,y,width2,height_n];
rect_Hz = [x2,y,width2,height_n];
y = y - height_n-vspace_n;
rect_PWG = [x1,y,width3,height_n];
rect_PWGnum = [x3,y,width3,height_n];
rect_PWGwt = [x4,y,width3,height_n];
y = y - height_n-vspace_n;
rect_plsm = [ x1,y,width3,height_n];
rect_MTTF = [ x3,y,width3,height_n];
rect_perp = [x4,y,width3,height_n];
y = y -(height_n+vspace_n);
rect_apply = [x1,y,width3,height_n];
rect_cancel = [x3,y,width3,height_n];
rect_clear_evecs = [x4,y,width3,height_n];
y = y -(2*height_n+vspace_n) - vspace_n;
rect_smth = [x1,y,2*width2+space_n,height_n];
onOff = {'off' 'on'};


hfig_evec_menu = figure('Position',rect_main,...
   'Name','Eigenvector Plot Options',...
   'NumberTitle','off','UserData',EV);

%  fosil code, that I don't want to deal with now
l_MTTF_old = l_MTTF;
l_perp_old = l_perp;

%  Frame
fwx = 5/evx;fwy = 5/evy;
fr=uicontrol(gcf,'Style','frame',...
   'Units','normalized',...
   'Position',[fwx,fwy,1-2*fwx,1-2*fwy],...
   'BackgroundColor',[0.5 0.5 0.5]);

%  # of eivenvectors : text  
tx1=uicontrol(gcf,'Style','text',...
   'String','# of evecs :  ',...
   'FontWeight','bold',...
   'Units','normalized',...
   'Position',rect_nevec1,...
   'BackgroundColor',[0.7 0.7 0.7]);

%  # of eivenvectors : edit
ed1=uicontrol(gcf,'Style','edit',...
   'String',num2str(EV.n_evec),...
   'FontWeight','bold',...
   'Units','normalized',...
   'Position',rect_nevec2,...
   'Tag','# Evec',...
   'CallBack','evecCbk');

%   reference resistivity : text
x2=uicontrol(gcf,'Style','text',...
   'Units','normalized',...
   'String','reference rho:  ',...
   'FontWeight','bold',...
   'Position',rect_rhor1,...
   'BackgroundColor',[0.7 0.7 0.7]);

%   reference resistivity : edit
ed2=uicontrol(gcf,'Style','edit',...
   'Units','normalized',...
   'String',num2str(EV.rho_ref),...
   'FontWeight','bold',...
   'Position',rect_rhor2,...
   'Tag','rho ref',...
   'CallBack','evecCbk');

%   SNR Units
sc=uicontrol(gcf,'Style','radio',...
   'Units','normalized',...
   'String','SNR Units',...
   'FontWeight','bold',...
   'Value',EV.snr_units,...
   'Position',rect_SNR,...
   'Tag','SNR units',...
   'CallBack','evecCbk');

%  polarization ellipse
pe=uicontrol(gcf,'Style','radio',...
   'String','Polariz. Ellipse',...
   'FontWeight','bold',...
   'Units','normalized',...
   'Value',EV.l_ellipse,...
   'Position',rect_pol,...
   'Tag','Ellipse/Vectors',...
   'CallBack','evecCbk');

%   impedance scaling
sc=uicontrol(gcf,'Style','radio',...
   'Units','normalized',...
   'String','Impedance Scale',...
   'FontWeight','bold',...
   'Value',EV.l_impNorm,...
   'Position',rect_impNorm,...
   'Tag','Impedance Scaling',...
   'CallBack','evecCbk');

%  PWG on/off
pe=uicontrol(gcf,'Style','radio',...
   'String','PWG',...
   'FontWeight','bold',...
   'Units','normalized',...
   'Value',EV.l_PWG,...
   'Position',rect_PWG,...
   'Tag','PWG',...
   'CallBack','evecCbk');

%  PWG : Number of evecs
pe=uicontrol(gcf,'Style','edit',...
   'String',num2str(EV.PWGnum),...
   'FontWeight','bold',...
   'Units','normalized',...
   'Position',rect_PWGnum,...
   'Tag','PWGnum',...
   'CallBack','evecCbk');

%  PWG : evalWt
pe=uicontrol(gcf,'Style','edit',...
   'String',num2str(EV.PWGevalWt),...
   'FontWeight','bold',...
   'Units','normalized',...
   'Position',rect_PWGwt,...
   'Tag','PWGevalWt',...
   'CallBack','evecCbk');

%  plot smoothed/separated eigenvectors
pe=uicontrol(gcf,'Style','radio',...
   'String','Smth/Sep Evecs',...
   'FontWeight','bold',...
   'Units','normalized',...
   'Enable',char(onOff(enable_pltsmth)),...
   'Tag','PLTSM',...
   'Value',l_smthsep,...
   'Position',rect_plsm,...
   'CallBack','evecCbk');

%  plot CN space as perp to smoothed evecs
pe=uicontrol(gcf,'Style','radio',...
   'String','Plot Hz',...
   'FontWeight','bold',...
   'Units','normalized',...
   'Tag','PlotHz',...
   'Value',EV.l_Hz,...
   'Position',rect_Hz,...
   'CallBack','evecCbk');

%  plot CN space as perp to smoothed evecs
pe=uicontrol(gcf,'Style','radio',...
   'String','Perp CN',...
   'FontWeight','bold',...
   'Units','normalized',...
   'Enable',char(onOff(enable_pltsmth)),...
   'Tag','PERP',...
   'Value',l_perp,...
   'Position',rect_perp,...
   'CallBack','evecCbk');

%  plot MT vecs as TFs relative to 1st site
pe=uicontrol(gcf,'Style','radio',...
   'String','MT TFs',...
   'FontWeight','bold',...
   'Units','normalized',...
   'Enable',char(onOff(enable_pltsmth)),...
   'Tag','MTTFs',...
   'Value',l_MTTF,...
   'Position',rect_MTTF,...
   'CallBack','evecCbk');

%  Apply changes
pb_apply=uicontrol(gcf,'Style','push',...
   'String','Apply',...
   'FontWeight','bold',...
   'Units','normalized',...
   'Position',rect_apply,...
   'Tag','Apply',...
   'CallBack','evecCbk');

%  Cancel Changes
pb_cancel=uicontrol(gcf,'Style','push',...
   'String','Cancel',...
   'FontWeight','bold',...
   'Tag','Cancel',...
   'Units','normalized',...
   'Position',rect_cancel,...
   'CallBack','evecCbk');

%  Clear Evec Figs
pb_clear=uicontrol(gcf,'Style','push',...
   'String','Clr Evec Figs',...
   'FontWeight','bold',...
   'Units','normalized',...
   'Tag','Clr Evec Figs',...
   'Position',rect_clear_evecs,...
   'CallBack','evecCbk');

%  Activate eigSM (smoothing program)
esm = uicontrol(gcf,'Style','pushbutton',...
   'String','Interactive Smoothing',...
   'FontWeight','bold',...
   'Units','normalized',...
   'Position',rect_smth,...
   'Tag','eigSM',...
   'Callback','evecCbk');

