hfig = gcf;
FigData = get(hfig,'UserData');
lims = FigData.lims;
theta = FigData.theta;
%   Partially edited to use a call back file,
%    and to get data needed for plot from user data
%    associated with figure (easy bookeeping for multiple
%        apresplt figure simultaneously);
%   MT is done, but not EMAP 

h_menu = figure('Position',[100,200,450,200],...
            'Name','Plot Options',...
            'NumberTitle','off','MenuBar','none');

lims_old = lims;
theta_old = theta;

bgc = [.8,.8,.8];

uicontrol(gcf,'Style','frame',...
            'Position',[.02,.02,.96,.96],...
            'Units','normalized');
%
uicontrol(h_menu,'Style','text',...
             'String','Period Range',...
             'Units','normalized',...
             'Position',[0.07 0.85 .25 0.10],...
             'HorizontalAlignment','Center');
         
uicontrol(h_menu,'Style','text',...
             'String','App. Res. Range',...
             'Units','normalized',...
             'Position',[0.39 0.85 .25 0.10],...
             'HorizontalAlignment','Center');

uicontrol(h_menu,'Style','text',...
             'String','Phase Range',...
             'Units','normalized',...
             'Position',[0.71 0.85 .22 0.10],...
             'HorizontalAlignment','Center');

h_lims = uicontrol(h_menu,'Style','edit',...
             'String',num2str(lims(1)),...
             'Units','normalized',...
             'Position',[0.03,.72,.14,.12],...
             'BackGroundColor',bgc,...
             'Tag','xMin',...
             'UserData',hfig,...
             'Callback','MTmenuCB');

h_lims = uicontrol(h_menu,'Style','edit',...
             'String',num2str(lims(2)),...
             'Units','normalized',...
             'Position',[0.18,.72,.14,.12],...
             'BackGroundColor',bgc,...
             'Tag','xMax',...
             'UserData',hfig,...
             'Callback','MTmenuCB');

h_lims = uicontrol(h_menu,'Style','edit',...
             'String',num2str(lims(3)),...
             'Units','normalized',...
             'Position',[0.38,.72,.14,.12],...
             'BackGroundColor',bgc,...
             'Tag','rhoMin',...
             'UserData',hfig,...
             'Callback','MTmenuCB');

h_lims = uicontrol(h_menu,'Style','edit',...
             'String',num2str(lims(4)),...
             'Units','normalized',...
             'Position',[0.53,.72,.14,.12],...
             'BackGroundColor',bgc,...
             'Tag','rhoMax',...
             'UserData',hfig,...
             'Callback','MTmenuCB');
             
h_lims = uicontrol(h_menu,'Style','edit',...
             'String',num2str(lims(5)),...
             'Units','normalized',...
             'Position',[0.73,.72,.10,.12],...
             'BackGroundColor',bgc,...
             'Tag','phiMin',...
             'UserData',hfig,...
             'Callback','MTmenuCB');

h_lims = uicontrol(h_menu,'Style','edit',...
             'String',num2str(lims(6)),...
             'Units','normalized',...
             'Position',[0.84,.72,.10,.12],...
             'BackGroundColor',bgc,...
             'Tag','phiMax',...
             'UserData',hfig,...
             'Callback','MTmenuCB');
             
uicontrol(h_menu,'Style','text',...
             'String','Rotation Angle',...
             'Units','normalized',...
             'Position',[0.20 0.50 .30 0.12],...
             'HorizontalAlignment','Center');

uicontrol(h_menu,'Style','edit',...
             'String',num2str(theta),...
             'Units','normalized',...
             'Position',[0.60,.50,.20,.12],...
             'BackGroundColor',bgc,...
             'Tag','theta',...
             'UserData',hfig,...
             'Callback','MTmenuCB');
             
if DipoleSetup == 'MT   '
   uicontrol(h_menu,'Style','Pushbutton','String','Plot',...
             'Units','normalized',...
             'Position',[0.07 .30 0.26 0.12],...
             'BackgroundColor',bgc,...
             'Tag','Plot',...
             'UserData',hfig,...
             'Callback','MTmenuCB');
else
   uicontrol(h_menu,'Style','Pushbutton','String','Plot',...
             'Units','normalized',...
             'Position',[0.07 .30 0.26 0.12],...
             'BackgroundColor',bgc,...
             'Callback','delete(h_menu);rpltem;');
end

uicontrol(h_menu,'Style','Pushbutton','String','Cancel',...
             'Units','normalized',...
             'Position',[0.37 .30 0.26 0.12],...
             'BackgroundColor',bgc,...
             'Tag','Cancel',...
             'UserData',hfig,...
             'Callback','MTmenuCB');
             
if DipoleSetup == 'MT   '             
  uicontrol(h_menu,'Style','Pushbutton','String','Quit',...
             'Units','normalized',...
             'Position',[0.67 .30 0.26 0.12],...
             'BackgroundColor',bgc,...
             'Tag','Quit',...
             'UserData',hfig,...
             'Callback','MTmenuCB');
else
  uicontrol(h_menu,'Style','Pushbutton','String','Quit',...
             'Units','normalized',...
             'Position',[0.67 .30 0.26 0.12],...
             'BackgroundColor',bgc,...
             'UserData',hfig,...
             'Callback',...
               'delete(h_menu);delete(hfig_xy);delete(hfig_yx)'); 
end   
  
if DipoleSetup == 'MT   '            
  uicontrol(h_menu,'Style','Pushbutton','String','New Plot',...
             'Units','normalized',...
             'Position',[0.37 .10 0.26 0.12],...
             'BackgroundColor',bgc,...
             'Tag','New Plot',...
             'UserData',hfig,...
             'Callback','MTmenuCB');
else
  uicontrol(h_menu,'Style','Pushbutton','String','New Plot',...
             'Units','normalized',...
             'Position',[0.37 .10 0.26 0.12],...
             'BackgroundColor',bgc,...
             'Callback',...
               'delete(h_menu);delete(hfig_xy);delete(hfig_yx),[cfile,dir] = uigetfile(fid);z_mtem');
end   

uicontrol(h_menu,'Style','Pushbutton','String','Add Band',...
             'Units','normalized',...
             'Position',[0.07 .10 0.26 0.12],...
             'BackgroundColor',bgc,...
             'Tag','Add Band',...
             'UserData',hfig,...
             'Callback','MTmenuCB');
