global alpha XX Xd Ruff X d

set(gcf,'pointer','watch');
[nt,dum,nb] = size(Sdms.U);
ReIm = 'real';
reim = 1;
npltmax = 10;
neig_plt = 5;
fac = 2;
nu = [1,1];
flambda_min = 30;     %    15 dB
flambda_set = 1.;
weights_changed = 0;

%function of evals ...  

fwt = 1./(((Sdms.lambda(1,:).*Sdms.lambda(2,:)).^.25).*sqrt(ndf'));
flambda = Sdms.lambda;
flambda = max(flambda,ones(size(flambda)));
flambda_scales = ones(size(flambda));
flambda(1:2,:) = max(flambda(1:2,:),flambda_min);
sigma = sqrt(Sdms.var);
setscls;
eigSMset;
stmonitr
Tlim = [ 10.^(t(1)-.1) 10.^(t(end)+.1)];

%  set up main figure
rect_main = [10,10,900,800];
rect_ch_menu = [.82,0,.15,.70];
rect_ch_plot = [.0,.0,.80,.80];
rect_flambda = [.05,.80,.5,.13];
rect_fit = [.60,.80,.25,.15];
height_1_ch = 20; space_1_ch = 3;
height_1_ch_n = height_1_ch/rect_main(4);
space_1_ch_n = space_1_ch/rect_main(4);
width_ch = .1;
width_damp = .035;
 l= 1;
polarization = 1;

hfig = figure('Position',rect_main,'Tag','EigSMfig','BackingStore','off')
x0 = rect_ch_menu(1);y0 = rect_ch_menu(2)+rect_ch_menu(4)-space_1_ch_n;
dx = width_ch; dy0 = height_1_ch_n;dy = height_1_ch_n + space_1_ch_n;
ctitle = [];
plot_ch = ones(nt,1);
plot_ch(1:2) = 0;
if nt > npltmax + 2
   plot_ch(npltmax+3:nt) = 0;
end
h_damp = zeros(2,nt);
rect = [ x0 y0-dy dx dy0];
rect_damp1 = [x0+dx y0-dy width_damp dy0];
rect_damp2 = [x0+dx+width_damp*1.1 y0-dy width_damp dy0];
 
h_txt = uicontrol('style','text', ...
     'parent',hfig,...
     'units','normalized',...
     'position',rect,...
     'string','Damp Fac',...
     'FontWeight','bold');
 
h_DAMP(1) = uicontrol('style','edit', ...
     'parent',hfig,...
     'units','normalized',...
     'position',rect_damp1,...
     'string',num2str(nu(1)),...
     'FontWeight','bold',...
     'FontSize',9,...
     'callback','');
 
h_DAMP(2) = uicontrol('style','edit', ...
     'parent',hfig,...
     'units','normalized',...
     'position',rect_damp2,...
     'string',num2str(nu(2)),...
     'FontWeight','bold',...
     'FontSize',9,...
     'Enable','off',...
     'callback','');

for k=3:nt
   rect = [ x0 y0-(k-1)*dy dx dy0];
   rect_damp1 = [x0+dx y0-(k-1)*dy width_damp dy0];
   rect_damp2 = [x0+dx+width_damp*1.1 y0-(k-1)*dy width_damp dy0];
   name = [csta(:,k)' '  ' chid(:,k)' ];
   ctitle = [ctitle ; name];

   h_ch(k) = uicontrol('style','checkbox', ...
     'parent',hfig,...
     'units','normalized',...
     'position',rect,...
     'string',name,...
     'FontWeight','bold',...
     'value',1,...
     'tag',['C' num2str(k)],...
     'callback','');

  h_damp(1,k) = uicontrol('style','edit', ...
     'parent',hfig,...
     'units','normalized',...
     'position',rect_damp1,...
     'string',num2str(nu_comp(1,k-2)),...
     'FontWeight','bold',...
     'FontSize',9,...
     'tag',['D' num2str(k)],...
     'callback','');

  h_damp(2,k) = uicontrol('style','edit', ...
     'parent',hfig,...
     'units','normalized',...
     'position',rect_damp2,...
     'string',num2str(nu_comp(2,k-2)),...
     'FontWeight','bold',...
     'FontSize',9,...
     'tag',['d' num2str(k)],...
     'Enable','off',...
     'callback','');
end  %  loop over channels 1:nt

rect = [ x0 y0+space_1_ch_n dx dy0 ];
h_recomp = uicontrol('style','pushbutton', ...
   'parent',hfig,...
   'units','normalized',...
   'position',rect,...
   'string','Recalc',...
   'FontWeight','bold',...
   'callback','eigSMcbk');

rect = [ x0 y0+space_1_ch_n+dy dx dy0 ];
h_replot = uicontrol('style','pushbutton', ...
   'parent',hfig,...
   'units','normalized',...
   'position',rect,...
   'string','Replot',...
   'FontWeight','bold',...
   'callback','eigSMcbk');

rect = [ x0+dx y0+space_1_ch_n width_damp dy0];
h_X = uicontrol('style','radiobutton', ...
   'parent',hfig,...
   'units','normalized',...
   'position',rect,...
   'string','X',...
   'FontWeight','bold',...
   'Value',1,...
   'callback','eigSMcbk');

rect = [ x0+dx+width_damp*1.1 y0+space_1_ch_n width_damp dy0];
h_Y = uicontrol('style','radiobutton', ...
   'parent',hfig,...
   'units','normalized',...
   'position',rect,...
   'string','Y',...
   'FontWeight','bold',...
   'Value',0,...
   'callback','eigSMcbk');

rect = [ x0+dx y0+space_1_ch_n+dy width_damp dy0];
h_REAL = uicontrol('style','radiobutton', ...
   'parent',hfig,...
   'units','normalized',...
   'position',rect,...
   'string','Re',...
   'FontWeight','bold',...
   'Value',1,...
   'callback','eigSMcbk');
 
rect = [ x0+dx+width_damp*1.1 y0+space_1_ch_n+dy width_damp dy0];
h_IMAG = uicontrol('style','radiobutton', ...
   'parent',hfig,...
   'units','normalized',...
   'position',rect,...
   'string','Im',...
   'FontWeight','bold',...
   'Value',0,...
   'callback','eigSMcbk');

rect = [ x0+dx*.5 y0+space_1_ch_n+2*dy dx dy0 ];
h_save_curves = uicontrol('style','pushbutton', ...
   'parent',hfig,...
   'units','normalized',...
   'position',rect,...
   'string','Save Curves',...
   'FontWeight','bold',...
   'callback','eigSMcbk');

rect = [ x0+dx*.5 y0+space_1_ch_n+3*dy dx dy0 ];
h_save_params = uicontrol('style','pushbutton', ...
   'parent',hfig,...
   'units','normalized',...
   'position',rect,...
   'string','Save Params',...
   'FontWeight','bold',...
   'callback','eigSMcbk');

rect = [ x0+dx*.5 y0+space_1_ch_n+4*dy dx dy0 ];
h_load = uicontrol('style','pushbutton', ...
   'parent',hfig,...
   'units','normalized',...
   'position',rect,...
   'string','Load Params',...
   'FontWeight','bold',...
   'callback','eigSMcbk');

rect = [ x0+dx*.5 y0+space_1_ch_n+5*dy dx dy0 ];
h_sep = uicontrol('style','pushbutton', ...
   'parent',hfig,...
   'units','normalized',...
   'position',rect,...
   'string','Separate',...
   'FontWeight','bold',...
   'callback','eigSMcbk');

[alpha,res,misfit,datsz] = eigSMfit(nu,nu_comp);
eigSMchk;
eigSMplt;

%  plot weights at top

h_flambda = axes('Position',rect_flambda,'Tag','FLAMBDA')
neig_plt = min(nt-1,neig_plt);
temp = [ flambda(1:neig_plt+1,:) flambda(1:neig_plt+1,nb) ];
pcolor(log10(temp))
set(gca,'FontWeight','bold')
cmap = jet(64);
%cmap = cmap(64:-1:1,:);
colormap(cmap);
%cl = [ min(min(- log10(temp))), max(max(-log10(temp)))];
%set(gca,'Clim',cl,'ClimMode','Manual');
colorbar;
Xcell = [1:nb+1];
Ycell = [1:neig_plt+1];

dx = width_ch;
dy = height_1_ch_n + space_1_ch_n;
x0 = rect_flambda(1);
y0 = rect_flambda(2)+rect_flambda(4)+dy/4;

rect = [ x0 y0 dx dy];
uicontrol('style','pushbutton', ...
   'parent',hfig,...
   'units','normalized',...
   'position',rect,...
   'string','ChngFac:',...
   'FontWeight','bold',...
   'callback','eigSMcbk');

rect = [ x0+dx*1.02 y0 dx/3 dy];
uicontrol('style','edit', ...
   'parent',hfig,...
   'units','normalized',...
   'position',rect,...
   'string',num2str(fac),...
   'FontWeight','bold',...
   'FontSize',9,...
   'callback','fac = str2num(get(gcbo,''string''))');

rect = [ x0+dx*1.37 y0 dx/2.8 dy];
uicontrol('style','pushbutton', ...
   'parent',hfig,...
   'units','normalized',...
   'position',rect,...
   'string','FBlk',...
   'FontWeight','bold',...
   'callback','eigSMcbk');

rect = [ x0+dx*1.80 y0 dx*.9 dy];
uicontrol('style','pushbutton', ...
   'parent',hfig,...
   'units','normalized',...
   'position',rect,...
   'string','SetWts:',...
   'FontWeight','bold',...
   'callback','eigSMcbk');

rect = [ x0+dx*2.72 y0 dx/3 dy];
uicontrol('style','edit', ...
   'parent',hfig,...
   'units','normalized',...
   'position',rect,...
   'string',num2str(flambda_set),...
   'FontWeight','bold',...
   'FontSize',9,...
   'callback','flambda_set = str2num(get(gcbo,''string''))');

rect = [ x0+dx*3.07 y0 dx/2.8 dy];
uicontrol('style','pushbutton', ...
   'parent',hfig,...
   'units','normalized',...
   'position',rect,...
   'string','SBlk',...
   'FontWeight','bold',...
   'callback','eigSMcbk');

rect = [ x0+dx*3.80 y0 dx*.9 dy];
uicontrol('style','pushbutton', ...
   'parent',hfig,...
   'units','normalized',...
   'position',rect,...
   'string','Reset Wts',...
   'FontWeight','bold',...
   'callback','eigSMcbk');

h_fit = axes('Position',rect_fit,'Tag','FIT')
temp = squeeze(Smth_dot(1:neig_plt,polarization,:));
temp = cumsum(temp);
semilogx(10.^t,temp(2:4,:));
set(gca,'Ylim',fit_lim,'FontWeight','bold','Xlim',Tlim);
fatlines(gca,2);
title('Eigenvector Fit')
legend('1-2','1-3','1-4',4)
set(gcf,'pointer','arrow');
