%path('/home/server/homes/pi/egbert/PKDSAOtst/matlab/EMTF/TVAR',path);
%path('/home/server/homes/pi/egbert/PKDSAOtst/matlab/EMTF/EQAR',path);
%path('/home/server/homes/pi/egbert/PKDSAOtst/matlab/EMTF/IN',path);
%path('/home/server/homes/pi/egbert/PKDSAOtst/matlab/EMTF/SDM',path);
path('/home/gauss/scratch/PKDSAOg/matlab/EMTF/TVAR',path);
path('/home/gauss/scratch/PKDSAOg/matlab/EMTF/EQAR',path);
path('/home/gauss/scratch/PKDSAOg/matlab/EMTF/IN',path);
path('/home/gauss/scratch/PKDSAOg/matlab/EMTF/SDM',path);
path('/home/gauss/scratch/PKDSAOg/matlab/EMTF/ZPLT',path);