sysTFtbl:	sysTFtbl.f getsp1.f systblsu.f resptbl1.f ../afcor.f fcor.inc ../inpu_bin.f ../inpu_asc.f
	f77 -o sysTFtbl sysTFtbl.f getsp1.f systblsu.f resptbl1.f ../afcor.f ../inpu_bin.f ../inpu_asc.f

clean:
	rm *.o sysTFtbl
