sys_tf_tbl:	sys_tf_tbl.f getsp.f systblsu.f ../../D/resptbl.f ../../D/afcor.f fcor.inc ../../D/inpu_bin.f ../../D/inpu_asc.f
	f77 -o sys_tf_tbl sys_tf_tbl.f getsp.f systblsu.f ../../D/resptbl.f ../../D/afcor.f ../../D/inpu_bin.f ../../D/inpu_asc.f

clean:
	rm *.o sys_tf_tbl
